# Created with YamlCreate.ps1 v2.1.3 using InputObject 🤖 $debug=QUSU.7-2-6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: ElijahLopez.MusicCaster
PackageVersion: 5.8.4
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Protocols:
- http
- https
ReleaseDate: 2022-10-10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/elibroftw/music-caster/releases/download/v5.8.4/Music.Caster.Setup.exe
  InstallerSha256: 4126B215A07FD6B6AC6A8BAEA49E3306D406A1CD565FED80E751604906241BC7
ManifestType: installer
ManifestVersion: 1.2.0
